version: '3.5'
services:
  app:
    environment:
      - HOME=/app
      - GEM_HOME=/app/vendor/bundle/ruby/2.5.0
      - BUNDLE_PATH=/app/vendor/bundle/ruby/2.5.0
      - PATH=/app/vendor/bundle/ruby/2.5.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - "TZ=Japan"
    build: .
    command: >
      /bin/bash -c "
        cd test/dummy &&
        rm -rf tmp/pids/server.pid &&
        rails s -p 3000 -b '0.0.0.0'
      "
    ports:
      - "4003:3000"
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - vendor:/app/vendor:cached
      - /app/.git
      - .ssh:/root/.ssh:rw
      - /app/.bundle
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '3325:3306'
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db:
    driver: local
  vendor:
    driver: local
